/**
 * generated by Xtext 2.10.0
 */
package tue.glt.boundingbox.dsl;

import tue.glt.boundingbox.dsl.BBDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BBDSLStandaloneSetup extends BBDSLStandaloneSetupGenerated {
  public static void doSetup() {
    BBDSLStandaloneSetup _bBDSLStandaloneSetup = new BBDSLStandaloneSetup();
    _bBDSLStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
