/**
 * generated by Xtext 2.10.0
 */
package tue.glt.boundingbox.dsl;

import tue.glt.boundingbox.dsl.AbstractBBDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class BBDSLRuntimeModule extends AbstractBBDSLRuntimeModule {
}
