/**
 * generated by Xtext 2.10.0
 */
package tue.glt.boundingbox.dsl.validation;

import tue.glt.boundingbox.dsl.validation.AbstractBBDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BBDSLValidator extends AbstractBBDSLValidator {
}
