/*
 * generated by Xtext 2.10.0
 */
package tue.glt.platoon.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import tue.glt.platoon.dsl.parser.antlr.internal.InternalPDSLParser;
import tue.glt.platoon.dsl.services.PDSLGrammarAccess;

public class PDSLParser extends AbstractAntlrParser {

	@Inject
	private PDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPDSLParser createParser(XtextTokenStream stream) {
		return new InternalPDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "World";
	}

	public PDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
