/*
 * generated by Xtext 2.10.0
 */
package tue.glt.platoon.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("tue/glt/platoon/dsl/parser/antlr/internal/InternalPDSL.tokens");
	}
}
