/*
 * generated by Xtext 2.10.0
 */
package tue.glt.boundingbox.dsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import tue.glt.boundingbox.dsl.ide.contentassist.antlr.internal.InternalBBDSLParser;
import tue.glt.boundingbox.dsl.services.BBDSLGrammarAccess;

public class BBDSLParser extends AbstractContentAssistParser {

	@Inject
	private BBDSLGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalBBDSLParser createParser() {
		InternalBBDSLParser result = new InternalBBDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getMoveAccess().getAlternatives(), "rule__Move__Alternatives");
					put(grammarAccess.getWorldAccess().getGroup(), "rule__World__Group__0");
					put(grammarAccess.getWorldAccess().getGroup_1(), "rule__World__Group_1__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getMoveLeftAccess().getGroup(), "rule__MoveLeft__Group__0");
					put(grammarAccess.getMoveRightAccess().getGroup(), "rule__MoveRight__Group__0");
					put(grammarAccess.getMoveDownAccess().getGroup(), "rule__MoveDown__Group__0");
					put(grammarAccess.getMoveUpAccess().getGroup(), "rule__MoveUp__Group__0");
					put(grammarAccess.getWorldAccess().getMoveCommandsAssignment_1_2(), "rule__World__MoveCommandsAssignment_1_2");
					put(grammarAccess.getWorldAccess().getMoveCommandsAssignment_1_3(), "rule__World__MoveCommandsAssignment_1_3");
					put(grammarAccess.getMoveLeftAccess().getDistanceAssignment_1(), "rule__MoveLeft__DistanceAssignment_1");
					put(grammarAccess.getMoveRightAccess().getDistanceAssignment_1(), "rule__MoveRight__DistanceAssignment_1");
					put(grammarAccess.getMoveDownAccess().getDistanceAssignment_1(), "rule__MoveDown__DistanceAssignment_1");
					put(grammarAccess.getMoveUpAccess().getDistanceAssignment_1(), "rule__MoveUp__DistanceAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalBBDSLParser typedParser = (InternalBBDSLParser) parser;
			typedParser.entryRuleWorld();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public BBDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BBDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
