/**
 * generated by Xtext 2.10.0
 */
package tue.glt.platoon.dsl;

import tue.glt.platoon.dsl.AbstractPDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PDSLRuntimeModule extends AbstractPDSLRuntimeModule {
}
