/**
 * generated by Xtext 2.10.0
 */
package tue.glt.platoon.dsl;

import tue.glt.platoon.dsl.PDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PDSLStandaloneSetup extends PDSLStandaloneSetupGenerated {
  public static void doSetup() {
    PDSLStandaloneSetup _pDSLStandaloneSetup = new PDSLStandaloneSetup();
    _pDSLStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
