/*
 * generated by Xtext 2.10.0
 */
package tue.glt.boundingbox.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBBDSLScopeProvider extends DelegatingScopeProvider {
}
