/*
 * generated by Xtext 2.10.0
 */
package tue.glt.platoon.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPDSLScopeProvider extends DelegatingScopeProvider {
}
