/*
 * generated by Xtext 2.10.0
 */
package tue.glt.platoon.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import tue.glt.platoon.dsl.ui.internal.DslActivator;

public class PDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("tue.glt.platoon.dsl.PDSL");
	}

}
