/**
 * generated by Xtext 2.10.0
 */
package tue.glt.boundingbox.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import tue.glt.boundingbox.dsl.ui.AbstractBBDSLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BBDSLUiModule extends AbstractBBDSLUiModule {
  public BBDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
