/**
 * generated by Xtext 2.10.0
 */
package tue.glt.platoon.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import tue.glt.platoon.dsl.ui.AbstractPDSLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PDSLUiModule extends AbstractPDSLUiModule {
  public PDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
