/**
 * generated by Xtext 2.10.0
 */
package tue.glt.platoon.dsl.ui.contentassist;

import tue.glt.platoon.dsl.ui.contentassist.AbstractPDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class PDSLProposalProvider extends AbstractPDSLProposalProvider {
}
