/**
 * generated by Xtext 2.10.0
 */
package tue.glt.boundingbox.dsl.scoping;

import tue.glt.boundingbox.dsl.scoping.AbstractBBDSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class BBDSLScopeProvider extends AbstractBBDSLScopeProvider {
}
