/*
 * generated by Xtext 2.10.0
 */
package tue.glt.platoon.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PDSLStandaloneSetup extends PDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new PDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
