/*
 * generated by Xtext 2.10.0
 */
package tue.glt.boundingbox.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import tue.glt.boundingbox.dsl.parser.antlr.internal.InternalBBDSLParser;
import tue.glt.boundingbox.dsl.services.BBDSLGrammarAccess;

public class BBDSLParser extends AbstractAntlrParser {

	@Inject
	private BBDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBBDSLParser createParser(XtextTokenStream stream) {
		return new InternalBBDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "World";
	}

	public BBDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BBDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
