/*
 * generated by Xtext 2.10.0
 */
package tue.glt.boundingbox.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BBDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("tue/glt/boundingbox/dsl/parser/antlr/internal/InternalBBDSL.tokens");
	}
}
